"""Photoshop-scale font registry — downloads, title list, reciter list."""

from __future__ import annotations

from dataclasses import dataclass

_GH = "https://raw.githubusercontent.com/google/fonts/main/ofl"


def _var(folder: str, base: str) -> tuple[str, str]:
    fname = f"{base}-Variable.ttf"
    url = f"{_GH}/{folder}/{base}%5Bwght%5D.ttf"
    return fname, url


def _static(folder: str, filename: str) -> tuple[str, str]:
    return filename, f"{_GH}/{folder}/{filename}"


def _opsz(folder: str, base: str) -> tuple[str, str]:
    fname = f"{base}-Variable.ttf"
    url = f"{_GH}/{folder}/{base}%5Bopsz,wght%5D.ttf"
    return fname, url


def _wide(folder: str, base: str) -> tuple[str, str]:
    fname = f"{base}-Variable.ttf"
    url = f"{_GH}/{folder}/{base}%5Bwdth,wght%5D.ttf"
    return fname, url


@dataclass(frozen=True)
class FontDef:
    id: str
    label: str
    filename: str
    weight: int | None = None
    size_scale: float = 1.0
    roles: frozenset[str] = frozenset({"title"})


def _t(id_: str, label: str, filename: str, weight: int | None = None, size_scale: float = 1.0) -> FontDef:
    return FontDef(id_, label, filename, weight, size_scale, frozenset({"title"}))


def _r(id_: str, label: str, filename: str, weight: int | None = None, size_scale: float = 1.0) -> FontDef:
    return FontDef(id_, label, filename, weight, size_scale, frozenset({"reciter"}))


def _b(id_: str, label: str, filename: str, weight: int | None = None, size_scale: float = 1.0) -> FontDef:
    return FontDef(id_, label, filename, weight, size_scale, frozenset({"title", "reciter"}))


# ── Download table (filename → URL) ───────────────────────────────────────────
_RAW_DOWNLOADS: list[tuple[str, str]] = [
    # Script / i18n (required)
    _static("amiri", "Amiri-Bold.ttf"),
    _wide("notosans", "NotoSans"),
    _var("notosanssc", "NotoSansSC"),
    _var("notosansjp", "NotoSansJP"),
    _var("notosanskr", "NotoSansKR"),
    _wide("notosansdevanagari", "NotoSansDevanagari"),
    _var("notosansbengali", "NotoSansBengali"),
    _var("notonaskharabic", "NotoNaskhArabic"),
    # Variable families
    _var("cinzel", "Cinzel"),
    _var("playfairdisplay", "PlayfairDisplay"),
    _var("cormorantgaramond", "CormorantGaramond"),
    _var("cormorant", "Cormorant"),
    _var("cormorantinfant", "CormorantInfant"),
    _var("cormorantsc", "CormorantSC"),
    _var("bodoniModa", "BodoniModa") if False else _opsz("bodonimoda", "BodoniModa"),
    _opsz("fraunces", "Fraunces"),
    _opsz("newsreader", "Newsreader"),
    _var("librebodoni", "LibreBodoni"),
    _var("librebaskerville", "LibreBaskerville"),
    _opsz("ebgaramond", "EBGaramond"),
    _static("ebgaramond", "EBGaramond-Italic-Variable.ttf") if False else (
        "EBGaramond-Italic-Variable.ttf",
        f"{_GH}/ebgaramond/EBGaramond-Italic%5Bwght%5D.ttf",
    ),
    _var("crimsonpro", "CrimsonPro"),
    _var("crimsontext", "CrimsonText"),
    _var("alegreya", "Alegreya"),
    _var("vollkorn", "Vollkorn"),
    _var("lora", "Lora"),
    _opsz("merriweather", "Merriweather"),
    _var("petrona", "Petrona"),
    _var("rokkitt", "Rokkitt"),
    _opsz("sourceserif4", "SourceSerif4"),
    _static("spectral", "Spectral-Regular.ttf"),
    _static("spectral", "Spectral-Bold.ttf"),
    _var("bitter", "Bitter"),
    _var("domine", "Domine"),
    _var("gelasio", "Gelasio"),
    _static("gentiumplus", "GentiumPlus-Regular.ttf"),
    _opsz("literata", "Literata"),
    _var("martel", "Martel"),
    _var("notoserif", "NotoSerif"),
    _static("ptserif", "PTSerif-Regular.ttf"),
    _static("ptserif", "PTSerif-Bold.ttf"),
    _var("tinos", "Tinos"),
    _var("trirong", "Trirong"),
    _var("ibmplexserif", "IBMPlexSerif"),
    _static("cardo", "Cardo-Regular.ttf"),
    _var("castoro", "Castoro"),
    _var("baskervville", "Baskervville"),
    _var("enriqueta", "Enriqueta"),
    _var("suranna", "Suranna"),
    _var("taviraj", "Taviraj"),
    _var("arvo", "Arvo"),
    _var("robtoslab", "RobotoSlab") if False else _var("robotoslab", "RobotoSlab"),
    _var("zillaslab", "ZillaSlab"),
    _var("josefinslab", "JosefinSlab"),
    _var("antonioc", "AnticSlab") if False else     _var("anticslab", "AnticSlab"),
    _static("ultra", "Ultra-Regular.ttf"),
    _var("sansita", "Sansita"),
    _var("inknutantiqua", "InknutAntiqua"),
    _var("josefinsans", "JosefinSans"),
    _var("raleway", "Raleway"),
    _var("outfit", "Outfit"),
    _var("spacegrotesk", "SpaceGrotesk"),
    _var("sora", "Sora"),
    _var("lexend", "Lexend"),
    _var("librefranklin", "LibreFranklin"),
    _var("catamaran", "Catamaran"),
    _var("quicksand", "Quicksand"),
    _var("jost", "Jost"),
    _var("montserrat", "Montserrat"),
    _var("nunitosans", "NunitoSans"),
    _var("sourcesans3", "SourceSans3"),
    _var("inter", "Inter"),
    _opsz("dmsans", "DMSans"),
    _var("karla", "Karla"),
    _var("manrope", "Manrope"),
    _wide("opensans", "OpenSans"),
    _static("poppins", "Poppins-Light.ttf"),
    _static("poppins", "Poppins-Regular.ttf"),
    _var("mulish", "Mulish"),
    _var("figtree", "Figtree"),
    _var("cabin", "Cabin"),
    _var("worksans", "WorkSans"),
    _var("publicsans", "PublicSans"),
    _var("albertsans", "AlbertSans"),
    _var("commissioner", "Commissioner"),
    _var("rubik", "Rubik"),
    _var("urbanist", "Urbanist"),
    _var("plusjakartasans", "PlusJakartaSans"),
    _var("redhatdisplay", "RedHatDisplay"),
    _var("barlow", "Barlow"),
    _var("exo2", "Exo2"),
    _var("overpass", "Overpass"),
    _var("titilliumweb", "TitilliumWeb"),
    _var("ubuntu", "Ubuntu"),
    _var("asap", "Asap"),
    _var("archivo", "Archivo"),
    _var("archivonarrow", "ArchivoNarrow"),
    _var("assistant", "Assistant"),
    _var("atkinsonhyperlegible", "AtkinsonHyperlegible"),
    _var("chivo", "Chivo"),
    _var("darker grotesque", "DarkerGrotesque") if False else _var("darkergrotesque", "DarkerGrotesque"),
    _var("encode sans", "EncodeSans") if False else _var("encodesans", "EncodeSans"),
    _var("epilogue", "Epilogue"),
    _var("familjengrotesk", "FamiljenGrotesk"),
    _var("golos text", "GolosText") if False else _var("golostext", "GolosText"),
    _var("heebo", "Heebo"),
    _var("hind", "Hind"),
    _var("ibmplexsans", "IBMPlexSans"),
    _var("inknutantiqua", "InknutAntiqua"),
    _var("kanit", "Kanit"),
    _var("lato", "Lato"),
    _var("league spartan", "LeagueSpartan") if False else _var("leaguespartan", "LeagueSpartan"),
    _var("libre caslon", "LibreCaslonText") if False else _var("librecaslontext", "LibreCaslonText"),
    _var("mada", "Mada"),
    _var("m PLUS 1p", "MPLUS1p") if False else _var("mplus1p", "MPLUS1p"),
    _var("mukta", "Mukta"),
    _var("nanum gothic", "NanumGothic") if False else _var("nanumgothic", "NanumGothic"),
    _var("noto sans display", "NotoSansDisplay") if False else _var("notosansdisplay", "NotoSansDisplay"),
    _var("nunito", "Nunito"),
    _var("oxygen", "Oxygen"),
    _var("pontano sans", "PontanoSans") if False else _var("pontanosans", "PontanoSans"),
    _var("prompt", "Prompt"),
    _var("proza libre", "ProzaLibre") if False else _var("prozalibre", "ProzaLibre"),
    _var("questrial", "Questrial"),
    _var("radio canada", "RadioCanada") if False else _var("radiocanada", "RadioCanada"),
    _var("raleway dots", "RalewayDots") if False else _static("ralewaydots", "RalewayDots-Regular.ttf"),
    _var("redhat text", "RedHatText") if False else _var("redhattext", "RedHatText"),
    _var("roboto", "Roboto"),
    _var("robotocondensed", "RobotoCondensed"),
    _var("rufina", "Rufina"),
    _var("sarabun", "Sarabun"),
    _var("signika", "Signika"),
    _var("sourcecodepro", "SourceCodePro"),
    _var("spartan", "Spartan") if False else _var("leaguespartan", "LeagueSpartan"),
    _var("syne", "Syne"),
    _var("teko", "Teko"),
    _var("thasadith", "Thasadith"),
    _var("voltaire", "Voltaire"),
    _var("wix madefor display", "WixMadeforDisplay") if False else _var("wixmadefordisplay", "WixMadeforDisplay"),
    _var("wix madefor text", "WixMadeforText") if False else _var("wixmadefortext", "WixMadeforText"),
    _var("yantramanav", "Yantramanav"),
    _var("zen kaku gothic", "ZenKakuGothicNew") if False else _var("zenkakugothicnew", "ZenKakuGothicNew"),
    # Static display / decorative
    _static("yesevaone", "YesevaOne-Regular.ttf"),
    _static("bebasneue", "BebasNeue-Regular.ttf"),
    _static("gloock", "Gloock-Regular.ttf"),
    _static("italiana", "Italiana-Regular.ttf"),
    _static("instrumentserif", "InstrumentSerif-Regular.ttf"),
    _static("dmserifdisplay", "DMSerifDisplay-Regular.ttf"),
    _static("anton", "Anton-Regular.ttf"),
    _static("poiretone", "PoiretOne-Regular.ttf"),
    _static("prata", "Prata-Regular.ttf"),
    _static("marcellus", "Marcellus-Regular.ttf"),
    _static("tenorsans", "TenorSans-Regular.ttf"),
    _static("cinzeldecorative", "CinzelDecorative-Regular.ttf"),
    _static("unifrakturmaguntia", "UnifrakturMaguntia-Book.ttf"),
    _static("abrildfatface", "AbrilFatface-Regular.ttf"),
    _static("bungee", "Bungee-Regular.ttf"),
    _static("bungeeinline", "BungeeInline-Regular.ttf"),
    _static("bungeeshade", "BungeeShade-Regular.ttf"),
    _static("calistoga", "Calistoga-Regular.ttf"),
    _static("cantataone", "CantataOne-Regular.ttf"),
    _static("chonburi", "Chonburi-Regular.ttf"),
    _static("concertone", "ConcertOne-Regular.ttf"),
    _static("flamenco", "Flamenco-Regular.ttf"),
    _static("frederickathegreat", "FrederickatheGreat-Regular.ttf"),
    _static("gildadisplay", "GildaDisplay-Regular.ttf"),
    _static("graduate", "Graduate-Regular.ttf"),
    _static("gravitasone", "GravitasOne-Regular.ttf"),
    _static("imprima", "Imprima-Regular.ttf"),
    _static("jockeyone", "JockeyOne-Regular.ttf"),
    _static("koulen", "Koulen-Regular.ttf"),
    _static("limelight", "Limelight-Regular.ttf"),
    _static("lobster", "Lobster-Regular.ttf"),
    _static("lobstertwo", "LobsterTwo-Regular.ttf"),
    _static("monoton", "Monoton-Regular.ttf"),
    _static("nosifer", "Nosifer-Regular.ttf"),
    _static("orbitron", "Orbitron-Variable.ttf") if False else (
        "Orbitron-Variable.ttf", f"{_GH}/orbitron/Orbitron%5Bwght%5D.ttf",
    ),
    _static("oswald", "Oswald-Variable.ttf") if False else (
        "Oswald-Variable.ttf", f"{_GH}/oswald/Oswald%5Bwght%5D.ttf",
    ),
    _static("pathwaygothicone", "PathwayGothicOne-Regular.ttf"),
    _static("patuaone", "PatuaOne-Regular.ttf"),
    _static("paytoneone", "PaytoneOne-Regular.ttf"),
    _static("permanentmarker", "PermanentMarker-Regular.ttf"),
    _static("philosopher", "Philosopher-Regular.ttf"),
    _static("pirataone", "PirataOne-Regular.ttf"),
    _static("plaster", "Plaster-Regular.ttf"),
    _static("pressstart2p", "PressStart2P-Regular.ttf"),
    _static("rakkas", "Rakkas-Regular.ttf"),
    _static("ranchers", "Ranchers-Regular.ttf"),
    _static("reemkufi", "ReemKufi-Regular.ttf"),
    _static("reemkufi", "ReemKufi-Variable.ttf") if False else (
        "ReemKufi-Variable.ttf", f"{_GH}/reemkufi/ReemKufi%5Bwght%5D.ttf",
    ),
    _static("righteous", "Righteous-Regular.ttf"),
    _static("ruslandisplay", "RuslanDisplay-Regular.ttf"),
    _static("rye", "Rye-Regular.ttf"),
    _static("saira", "Saira-Variable.ttf") if False else (
        "Saira-Variable.ttf", f"{_GH}/saira/Saira%5Bwdth,wght%5D.ttf",
    ),
    _static("sairastencilone", "SairaStencilOne-Regular.ttf"),
    _static("sancreek", "Sancreek-Regular.ttf"),
    _static("shrikhand", "Shrikhand-Regular.ttf"),
    _static("sigmar", "Sigmar-Regular.ttf"),
    _static("smokum", "Smokum-Regular.ttf"),
    _static("snowburstone", "SnowburstOne-Regular.ttf"),
    _static("spicyrice", "SpicyRice-Regular.ttf"),
    _static("stardosstencil", "StardosStencil-Regular.ttf"),
    _static("sticknobills", "StickNoBills-Variable.ttf") if False else (
        "StickNoBills-Variable.ttf", f"{_GH}/sticknobills/StickNoBills%5Bwght%5D.ttf",
    ),
    _static("titanone", "TitanOne-Regular.ttf"),
    _static("uncialantiqua", "UncialAntiqua-Regular.ttf"),
    _static("vastshadow", "VastShadow-Regular.ttf"),
    _static("vidaloka", "Vidaloka-Regular.ttf"),
    _static("vollkornsc", "VollkornSC-Regular.ttf"),
    _static("wellfleet", "Wellfleet-Regular.ttf"),
    _static("wendyone", "WendyOne-Regular.ttf"),
    _static("yeonsung", "YeonSung-Regular.ttf"),
    _static("zenantique", "ZenAntique-Regular.ttf"),
    _static("zenantiquesoft", "ZenAntiqueSoft-Regular.ttf"),
    _static("zcoolkuaile", "ZCOOLKuaiLe-Regular.ttf"),
    _static("zcoolqingkehuangyou", "ZCOOLQingKeHuangYou-Regular.ttf"),
    _static("zcoolxiaowei", "ZCOOLXiaoWei-Regular.ttf"),
    _static("satisfy", "Satisfy-Regular.ttf"),
    _static("pacifico", "Pacifico-Regular.ttf"),
    _static("greatvibes", "GreatVibes-Regular.ttf"),
    _static("alexbrush", "AlexBrush-Regular.ttf"),
    _static("allura", "Allura-Regular.ttf"),
    _static("cookie", "Cookie-Regular.ttf"),
    _static("tangerine", "Tangerine-Regular.ttf"),
    _static("cinzel decorative", "CinzelDecorative-Bold.ttf") if False else _static(
        "cinzeldecorative", "CinzelDecorative-Bold.ttf",
    ),
    _static("dm serif text", "DMSerifText-Regular.ttf") if False else _static("dmseriftext", "DMSerifText-Regular.ttf"),
    _static("fanwood text", "FanwoodText-Regular.ttf") if False else _static("fanwoodtext", "FanwoodText-Regular.ttf"),
    _static("fanwood text", "FanwoodText-Italic.ttf") if False else _static("fanwoodtext", "FanwoodText-Italic.ttf"),
    _static("goudybookletter1911", "GoudyBookletter1911-Regular.ttf"),
    _static("halant", "Halant-Regular.ttf"),
    _static("halant", "Halant-Bold.ttf"),
    _static("hepta slab", "HeptaSlab-Variable.ttf") if False else (
        "HeptaSlab-Variable.ttf", f"{_GH}/heptaslab/HeptaSlab%5Bwght%5D.ttf",
    ),
    _static("imbue", "Imbue-Variable.ttf") if False else (
        "Imbue-Variable.ttf", f"{_GH}/imbue/Imbue%5Bopsz,wght%5D.ttf",
    ),
    _static("karma", "Karma-Regular.ttf"),
    _static("karma", "Karma-Bold.ttf"),
    _static("kreon", "Kreon-Variable.ttf") if False else (
        "Kreon-Variable.ttf", f"{_GH}/kreon/Kreon%5Bwght%5D.ttf",
    ),
    _static("lemonada", "Lemonada-Variable.ttf") if False else (
        "Lemonada-Variable.ttf", f"{_GH}/lemonada/Lemonada%5Bwght%5D.ttf",
    ),
    _static("mclaren", "McLaren-Regular.ttf"),
    _static("medulaone", "MedulaOne-Regular.ttf"),
    _static("metamorphous", "Metamorphous-Regular.ttf"),
    _static("metrophobic", "Metrophobic-Regular.ttf"),
    _static("mirza", "Mirza-Regular.ttf"),
    _static("mitr", "Mitr-Regular.ttf"),
    _static("neuton", "Neuton-Regular.ttf"),
    _static("neuton", "Neuton-Bold.ttf"),
    _static("noticia text", "NoticiaText-Regular.ttf") if False else _static("noticiatext", "NoticiaText-Regular.ttf"),
    _static("oldenburg", "Oldenburg-Regular.ttf"),
    _static("oleoscript", "OleoScript-Regular.ttf"),
    _static("oleoscript", "OleoScript-Bold.ttf"),
    _static("pompiere", "Pompiere-Regular.ttf"),
    _static("portlligat sans", "PortLligatSans-Regular.ttf") if False else _static(
        "portlligatsans", "PortLligatSans-Regular.ttf",
    ),
    _static("prociono", "Prociono-Regular.ttf"),
    _static("quando", "Quando-Regular.ttf"),
    _static("quattrocento", "Quattrocento-Regular.ttf"),
    _static("quattrocento sans", "QuattrocentoSans-Regular.ttf") if False else _static(
        "quattrocentosans", "QuattrocentoSans-Regular.ttf",
    ),
    _static("radley", "Radley-Regular.ttf"),
    _static("rajdhani", "Rajdhani-Regular.ttf"),
    _static("rajdhani", "Rajdhani-Bold.ttf"),
    _static("rancho", "Rancho-Regular.ttf"),
    _static("rasa", "Rasa-Variable.ttf") if False else (
        "Rasa-Variable.ttf", f"{_GH}/rasa/Rasa%5Bwdth,wght%5D.ttf",
    ),
    _static("rhodiumlibre", "RhodiumLibre-Regular.ttf"),
    _static("rozhaone", "RozhaOne-Regular.ttf"),
    _static("rubikmonoone", "RubikMonoOne-Regular.ttf"),
    _static("rufina", "Rufina-Regular.ttf"),
    _static("sail", "Sail-Regular.ttf"),
    _static("sanchez", "Sanchez-Regular.ttf"),
    _static("sarala", "Sarala-Regular.ttf"),
    _static("sarala", "Sarala-Bold.ttf"),
    _static("secularone", "SecularOne-Regular.ttf"),
    _static("sedan", "Sedan-Regular.ttf"),
    _static("sedan", "SedanSC-Regular.ttf") if False else _static("sedansc", "SedanSC-Regular.ttf"),
    _static("sen", "Sen-Variable.ttf") if False else (
        "Sen-Variable.ttf", f"{_GH}/sen/Sen%5Bwght%5D.ttf",
    ),
    _static("sharetech", "ShareTech-Regular.ttf"),
    _static("sharetechmono", "ShareTechMono-Regular.ttf"),
    _static("shortstack", "ShortStack-Regular.ttf"),
    _static("silkscreen", "Silkscreen-Regular.ttf"),
    _static("sniglet", "Sniglet-Regular.ttf"),
    _static("sora", "Sora-Variable.ttf") if False else _var("sora", "Sora"),
    _static("sortsmillgoudy", "SortsMillGoudy-Regular.ttf"),
    _static("special elite", "SpecialElite-Regular.ttf") if False else _static("specialelite", "SpecialElite-Regular.ttf"),
    _static("squadaone", "SquadaOne-Regular.ttf"),
    _static("stintultracondensed", "StintUltraCondensed-Regular.ttf"),
    _static("stoke", "Stoke-Regular.ttf"),
    _static("sumana", "Sumana-Regular.ttf"),
    _static("sura", "Sura-Regular.ttf"),
    _static("sura", "Sura-Bold.ttf"),
    _static("syncopate", "Syncopate-Regular.ttf"),
    _static("syncopate", "Syncopate-Bold.ttf"),
    _static("tienne", "Tienne-Regular.ttf"),
    _static("tienne", "Tienne-Bold.ttf"),
    _static("trocchi", "Trocchi-Regular.ttf"),
    _static("trykker", "Trykker-Regular.ttf"),
    _static("unicaone", "UnicaOne-Regular.ttf"),
    _static("unna", "Unna-Regular.ttf"),
    _static("varta", "Varta-Variable.ttf") if False else (
        "Varta-Variable.ttf", f"{_GH}/varta/Varta%5Bwght%5D.ttf",
    ),
    _static("vesperlibre", "VesperLibre-Regular.ttf"),
    _static("volkhov", "Volkhov-Regular.ttf"),
    _static("volkhov", "Volkhov-Bold.ttf"),
    _static("voltaire", "Voltaire-Regular.ttf"),
    _static("wallpoet", "Wallpoet-Regular.ttf"),
    _static("warnes", "Warnes-Regular.ttf"),
    _static("yeonsung", "YeonSung-Regular.ttf"),
    _static("yrsa", "Yrsa-Variable.ttf") if False else (
        "Yrsa-Variable.ttf", f"{_GH}/yrsa/Yrsa%5Bwght%5D.ttf",
    ),
    _static("zilla slab highlight", "ZillaSlabHighlight-Regular.ttf") if False else _static(
        "zillaslabhighlight", "ZillaSlabHighlight-Regular.ttf",
    ),
]

FONT_DOWNLOADS: dict[str, str] = dict(_RAW_DOWNLOADS)

# ── Font picker registry ──────────────────────────────────────────────────────
FONT_REGISTRY: tuple[FontDef, ...] = (
    # ── Title: serif & editorial ──
    _t("cinzel", "Cinzel — Roman inscription", "Cinzel-Variable.ttf", 400),
    _t("playfair", "Playfair Display — editorial luxury", "PlayfairDisplay-Variable.ttf", 400),
    _t("cormorant_garamond", "Cormorant Garamond — refined classic", "CormorantGaramond-Variable.ttf", 500),
    _t("cormorant", "Cormorant — airy display serif", "Cormorant-Variable.ttf", 500),
    _t("cormorant_sc", "Cormorant SC — small caps elegance", "CormorantSC-Variable.ttf", 500),
    _t("cormorant_infant", "Cormorant Infant — gentle storybook", "CormorantInfant-Variable.ttf", 500),
    _t("bodoni_moda", "Bodoni Moda — high-fashion contrast", "BodoniModa-Variable.ttf", 500),
    _t("libre_bodoni", "Libre Bodoni — Italian magazine", "LibreBodoni-Variable.ttf", 500),
    _t("libre_baskerville", "Libre Baskerville — timeless book", "LibreBaskerville-Variable.ttf", 400),
    _t("eb_garamond", "EB Garamond — bookish warmth", "EBGaramond-Variable.ttf", 500),
    _t("crimson_pro", "Crimson Pro — heritage volume", "CrimsonPro-Variable.ttf", 600),
    _t("crimson_text", "Crimson Text — old-style prose", "CrimsonText-Variable.ttf", 600),
    _t("alegreya", "Alegreya — calligraphic rhythm", "Alegreya-Variable.ttf", 500),
    _t("vollkorn", "Vollkorn — grave old-style", "Vollkorn-Variable.ttf", 600),
    _t("vollkorn_sc", "Vollkorn SC — small caps gravitas", "VollkornSC-Regular.ttf"),
    _t("lora", "Lora — warm contemporary", "Lora-Variable.ttf", 500),
    _t("merriweather", "Merriweather — sturdy headline", "Merriweather-Variable.ttf", 700),
    _t("petrona", "Petrona — narrative warmth", "Petrona-Variable.ttf", 500),
    _t("rokkitt", "Rokkitt — geometric slab", "Rokkitt-Variable.ttf", 600),
    _t("source_serif", "Source Serif 4 — modern book", "SourceSerif4-Variable.ttf", 600),
    _t("spectral_bold", "Spectral Bold — crisp literary", "Spectral-Bold.ttf"),
    _t("bitter", "Bitter — slab serif punch", "Bitter-Variable.ttf", 600),
    _t("domine", "Domine — newspaper classic", "Domine-Variable.ttf", 600),
    _t("gelasio", "Gelasio — Georgia alternative", "Gelasio-Variable.ttf", 500),
    _t("gentium_plus", "Gentium Plus — dignified Latin", "GentiumPlus-Regular.ttf"),
    _t("literata", "Literata — e-reader prose", "Literata-Variable.ttf", 500),
    _t("martel", "Martel — Nepalese elegance", "Martel-Variable.ttf", 600),
    _t("noto_serif", "Noto Serif — universal serif", "NotoSerif-Variable.ttf", 600),
    _t("pt_serif", "PT Serif — Russian editorial", "PTSerif-Bold.ttf"),
    _t("tinos", "Tinos — metric-compatible classic", "Tinos-Variable.ttf", 600),
    _t("trirong", "Trirong — Thai-inspired serif", "Trirong-Variable.ttf", 500),
    _t("ibm_plex_serif", "IBM Plex Serif — corporate book", "IBMPlexSerif-Variable.ttf", 500),
    _t("cardo", "Cardo — scholarly classic", "Cardo-Regular.ttf"),
    _t("castoro", "Castoro — renaissance book", "Castoro-Variable.ttf", 400),
    _t("baskervville", "Baskervville — revival Baskerville", "Baskervville-Variable.ttf", 400),
    _t("enriqueta", "Enriqueta — slab headline", "Enriqueta-Variable.ttf", 600),
    _t("suranna", "Suranna — Telugu elegance", "Suranna-Variable.ttf", 400),
    _t("taviraj", "Taviraj — Thai editorial", "Taviraj-Variable.ttf", 500),
    _t("arvo", "Arvo — geometric slab", "Arvo-Variable.ttf", 700),
    _t("roboto_slab", "Roboto Slab — modern slab", "RobotoSlab-Variable.ttf", 600),
    _t("zilla_slab", "Zilla Slab — Mozilla book", "ZillaSlab-Variable.ttf", 600),
    _t("josefin_slab", "Josefin Slab — art-deco slab", "JosefinSlab-Variable.ttf", 500),
    _t("antic_slab", "Antic Slab — rounded slab", "AnticSlab-Variable.ttf", 400),
    _t("hepta_slab", "Hepta Slab — variable slab", "HeptaSlab-Variable.ttf", 600),
    _t("kreon", "Kreon — newspaper slab", "Kreon-Variable.ttf", 600),
    _t("fanwood", "Fanwood Text — vintage book", "FanwoodText-Regular.ttf"),
    _t("fanwood_italic", "Fanwood Italic — vintage italic", "FanwoodText-Italic.ttf"),
    _t("dm_serif_text", "DM Serif Text — compact classic", "DMSerifText-Regular.ttf"),
    _t("goudy_bookletter", "Goudy Bookletter — antique print", "GoudyBookletter1911-Regular.ttf"),
    _t("halant", "Halant — Devanagari serif", "Halant-Bold.ttf"),
    _t("imbue", "Imbue — ultra-contrast display", "Imbue-Variable.ttf", 500),
    _t("karma", "Karma — contemporary serif", "Karma-Bold.ttf"),
    _t("neuton", "Neuton — soft book face", "Neuton-Bold.ttf"),
    _t("noticia_text", "Noticia Text — news serif", "NoticiaText-Regular.ttf"),
    _t("prociono", "Prociono — Baskerville-like", "Prociono-Regular.ttf"),
    _t("quattrocento", "Quattrocento — Renaissance", "Quattrocento-Regular.ttf"),
    _t("radley", "Radley — wood type revival", "Radley-Regular.ttf"),
    _t("rasa", "Rasa — Gujarati-influenced", "Rasa-Variable.ttf", 500),
    _t("rhodium_libre", "Rhodium Libre — display serif", "RhodiumLibre-Regular.ttf"),
    _t("rozha_one", "Rozha One — heavy display", "RozhaOne-Regular.ttf"),
    _t("sorts_mill_goudy", "Sorts Mill Goudy — Goudy revival", "SortsMillGoudy-Regular.ttf"),
    _t("stoke", "Stoke — weathered serif", "Stoke-Regular.ttf"),
    _t("sumana", "Sumana — Devanagari book", "Sumana-Regular.ttf"),
    _t("sura", "Sura — Devanagari headline", "Sura-Bold.ttf"),
    _t("tienne", "Tienne — renaissance display", "Tienne-Bold.ttf"),
    _t("trocchi", "Trocchi — short display", "Trocchi-Regular.ttf"),
    _t("trykker", "Trykker — poster slab", "Trykker-Regular.ttf"),
    _t("unna", "Unna — gentle editorial", "Unna-Regular.ttf"),
    _t("vesper_libre", "Vesper Libre — high contrast", "VesperLibre-Regular.ttf"),
    _t("volkhov", "Volkhov — sturdy display", "Volkhov-Bold.ttf"),
    _t("yrsa", "Yrsa — Nordic warmth", "Yrsa-Variable.ttf", 500),
    _t("fraunces", "Fraunces — soft vintage display", "Fraunces-Variable.ttf", 500),
    _t("newsreader", "Newsreader — newspaper grace", "Newsreader-Variable.ttf", 500),
    _t("instrument_serif", "Instrument Serif — fashion editorial", "InstrumentSerif-Regular.ttf"),
    _t("dm_serif_display", "DM Serif Display — poster classic", "DMSerifDisplay-Regular.ttf"),
    _t("prata", "Prata — dramatic contrast", "Prata-Regular.ttf"),
    _t("marcellus", "Marcellus — temple inscription", "Marcellus-Regular.ttf"),
    _t("gilda_display", "Gilda Display — art-deco luxury", "GildaDisplay-Regular.ttf"),
    _t("fanwood_display", "Fanwood — library classic", "FanwoodText-Regular.ttf"),
    # ── Title: display, condensed, decorative ──
    _t("yeseva_one", "Yeseva One — ornate display", "YesevaOne-Regular.ttf", size_scale=1.12),
    _t("bebas_neue", "Bebas Neue — cinematic caps", "BebasNeue-Regular.ttf", size_scale=1.45),
    _t("gloock", "Gloock — heavy editorial", "Gloock-Regular.ttf", size_scale=1.12),
    _t("italiana", "Italiana — art-deco caps", "Italiana-Regular.ttf", size_scale=1.08),
    _t("anton", "Anton — bold condensed", "Anton-Regular.ttf", size_scale=1.35),
    _t("poiret_one", "Poiret One — thin art-deco", "PoiretOne-Regular.ttf", size_scale=1.18),
    _t("tenor_sans", "Tenor Sans — minimalist caps", "TenorSans-Regular.ttf", size_scale=1.12),
    _t("cinzel_decorative", "Cinzel Decorative — gilded caps", "CinzelDecorative-Regular.ttf", size_scale=1.1),
    _t("cinzel_decorative_bold", "Cinzel Decorative Bold — ornate", "CinzelDecorative-Bold.ttf", size_scale=1.1),
    _t("unifraktur", "Unifraktur Maguntia — blackletter", "UnifrakturMaguntia-Book.ttf", size_scale=1.15),
    _t("abril_fatface", "Abril Fatface — fat display", "AbrilFatface-Regular.ttf", size_scale=1.1),
    _t("bungee", "Bungee — urban billboard", "Bungee-Regular.ttf", size_scale=1.15),
    _t("bungee_inline", "Bungee Inline — outlined", "BungeeInline-Regular.ttf", size_scale=1.1),
    _t("bungee_shade", "Bungee Shade — dimensional", "BungeeShade-Regular.ttf", size_scale=1.1),
    _t("calistoga", "Calistoga — Western display", "Calistoga-Regular.ttf"),
    _t("cantata_one", "Cantata One — Spanish display", "CantataOne-Regular.ttf"),
    _t("chonburi", "Chonburi — Thai display", "Chonburi-Regular.ttf"),
    _t("concert_one", "Concert One — rounded display", "ConcertOne-Regular.ttf"),
    _t("flamenco", "Flamenco — flamenco poster", "Flamenco-Regular.ttf"),
    _t("fredericka", "Fredericka the Great — Victorian", "FrederickatheGreat-Regular.ttf"),
    _t("graduate", "Graduate — varsity block", "Graduate-Regular.ttf", size_scale=1.1),
    _t("gravitas_one", "Gravitas One — ultra heavy", "GravitasOne-Regular.ttf"),
    _t("jockey_one", "Jockey One — Western sans", "JockeyOne-Regular.ttf", size_scale=1.1),
    _t("koulen", "Koulen — Khmer display", "Koulen-Regular.ttf", size_scale=1.2),
    _t("limelight", "Limelight — art-deco glow", "Limelight-Regular.ttf"),
    _t("lobster", "Lobster — script display", "Lobster-Regular.ttf"),
    _t("lobster_two", "Lobster Two — bold script", "LobsterTwo-Regular.ttf"),
    _t("monoton", "Monoton — neon strip", "Monoton-Regular.ttf", size_scale=1.1),
    _t("nosifer", "Nosifer — horror display", "Nosifer-Regular.ttf"),
    _t("orbitron", "Orbitron — sci-fi geometric", "Orbitron-Variable.ttf", 700),
    _t("oswald", "Oswald — condensed gothic", "Oswald-Variable.ttf", 500, 1.25),
    _t("pathway_gothic", "Pathway Gothic One — narrow", "PathwayGothicOne-Regular.ttf", size_scale=1.15),
    _t("patua_one", "Patua One — rounded slab display", "PatuaOne-Regular.ttf"),
    _t("paytone_one", "Paytone One — sporty display", "PaytoneOne-Regular.ttf"),
    _t("permanent_marker", "Permanent Marker — hand lettered", "PermanentMarker-Regular.ttf"),
    _t("philosopher", "Philosopher — mystical sans", "Philosopher-Regular.ttf"),
    _t("pirata_one", "Pirata One — pirate gothic", "PirataOne-Regular.ttf"),
    _t("plaster", "Plaster — condensed block", "Plaster-Regular.ttf", size_scale=1.15),
    _t("press_start", "Press Start 2P — pixel retro", "PressStart2P-Regular.ttf", size_scale=0.85),
    _t("rakkas", "Rakkas — Arabic display", "Rakkas-Regular.ttf"),
    _t("ranchers", "Ranchers — Western slab", "Ranchers-Regular.ttf"),
    _t("reem_kufi", "Reem Kufi — Kufi display", "ReemKufi-Variable.ttf", 600),
    _t("righteous", "Righteous — retro futuristic", "Righteous-Regular.ttf"),
    _t("ruslan_display", "Ruslan Display — Cyrillic display", "RuslanDisplay-Regular.ttf"),
    _t("rye", "Rye — wood type Western", "Rye-Regular.ttf"),
    _t("saira", "Saira — variable sans display", "Saira-Variable.ttf", 700),
    _t("saira_stencil", "Saira Stencil One — military", "SairaStencilOne-Regular.ttf", size_scale=1.1),
    _t("sancreek", "Sancreek — Western serif", "Sancreek-Regular.ttf"),
    _t("shrikhand", "Shrikhand — Gujarati display", "Shrikhand-Regular.ttf"),
    _t("sigmar", "Sigmar — bubble display", "Sigmar-Regular.ttf"),
    _t("smokum", "Smokum — Western poster", "Smokum-Regular.ttf"),
    _t("snowburst", "Snowburst One — psychedelic", "SnowburstOne-Regular.ttf"),
    _t("spicy_rice", "Spicy Rice — Thai display", "SpicyRice-Regular.ttf"),
    _t("stardos_stencil", "Stardos Stencil — military", "StardosStencil-Regular.ttf"),
    _t("stick_no_bills", "Stick No Bills — Sinhala display", "StickNoBills-Variable.ttf", 600),
    _t("titan_one", "Titan One — cartoon display", "TitanOne-Regular.ttf"),
    _t("uncial_antiqua", "Uncial Antiqua — medieval", "UncialAntiqua-Regular.ttf"),
    _t("ultra", "Ultra — wood type", "Ultra-Regular.ttf"),
    _t("vast_shadow", "Vast Shadow — 3D shadow", "VastShadow-Regular.ttf"),
    _t("vidaloka", "Vidaloka — curvy display", "Vidaloka-Regular.ttf"),
    _t("wellfleet", "Wellfleet — poster serif", "Wellfleet-Regular.ttf"),
    _t("wendy_one", "Wendy One — playful display", "WendyOne-Regular.ttf"),
    _t("yeonsung", "Yeon Sung — Korean display", "YeonSung-Regular.ttf"),
    _t("zen_antique", "Zen Antique — Japanese classic", "ZenAntique-Regular.ttf"),
    _t("zen_antique_soft", "Zen Antique Soft — soft classic", "ZenAntiqueSoft-Regular.ttf"),
    _t("zcool_kuaile", "ZCOOL KuaiLe — Chinese playful", "ZCOOLKuaiLe-Regular.ttf"),
    _t("zcool_huangyou", "ZCOOL QingKe HuangYou — Chinese bold", "ZCOOLQingKeHuangYou-Regular.ttf"),
    _t("zcool_xiaowei", "ZCOOL XiaoWei — Chinese serif", "ZCOOLXiaoWei-Regular.ttf"),
    _t("satisfy", "Satisfy — brush script", "Satisfy-Regular.ttf"),
    _t("pacifico", "Pacifico — surf script", "Pacifico-Regular.ttf"),
    _t("great_vibes", "Great Vibes — calligraphy", "GreatVibes-Regular.ttf"),
    _t("alex_brush", "Alex Brush — formal script", "AlexBrush-Regular.ttf"),
    _t("allura", "Allura — flowing script", "Allura-Regular.ttf"),
    _t("cookie", "Cookie — casual script", "Cookie-Regular.ttf"),
    _t("tangerine", "Tangerine — delicate script", "Tangerine-Regular.ttf", size_scale=1.3),
    _t("medula_one", "Medula One — condensed gothic", "MedulaOne-Regular.ttf", size_scale=1.2),
    _t("metamorphous", "Metamorphous — fantasy serif", "Metamorphous-Regular.ttf"),
    _t("oldenburg", "Oldenburg — blackletter display", "Oldenburg-Regular.ttf"),
    _t("oleo_script", "Oleo Script — bouncy script", "OleoScript-Bold.ttf"),
    _t("pompiere", "Pompiere — art-deco thin", "Pompiere-Regular.ttf", size_scale=1.15),
    _t("quando", "Quando — Venetian display", "Quando-Regular.ttf"),
    _t("rancho", "Rancho — Western script", "Rancho-Regular.ttf"),
    _t("rubik_mono", "Rubik Mono One — block mono", "RubikMonoOne-Regular.ttf", size_scale=0.9),
    _t("secular_one", "Secular One — Hebrew display", "SecularOne-Regular.ttf"),
    _t("sedan_sc", "Sedan SC — small caps display", "SedanSC-Regular.ttf"),
    _t("special_elite", "Special Elite — typewriter", "SpecialElite-Regular.ttf"),
    _t("squada_one", "Squada One — ultra condensed", "SquadaOne-Regular.ttf", size_scale=1.25),
    _t("stint_ultra", "Stint Ultra Condensed — narrow", "StintUltraCondensed-Regular.ttf", size_scale=1.2),
    _t("syncopate_bold", "Syncopate Bold — spaced caps", "Syncopate-Bold.ttf", size_scale=1.1),
    _t("unica_one", "Unica One — art-gothic", "UnicaOne-Regular.ttf", size_scale=1.1),
    _t("wallpoet", "Wallpoet — pixel grid", "Wallpoet-Regular.ttf"),
    _t("warnes", "Warnes — 3D carnival", "Warnes-Regular.ttf"),
    _t("zilla_highlight", "Zilla Slab Highlight — inline", "ZillaSlabHighlight-Regular.ttf"),
    _t("sansita", "Sansita — friendly display", "Sansita-Variable.ttf", 700),
    _t("inknut_antiqua", "Inknut Antiqua — Devanagari display", "InknutAntiqua-Variable.ttf", 600),
    _t("montserrat_bold", "Montserrat Bold — geometric caps", "Montserrat-Variable.ttf", 700),
    _t("archivo_black", "Archivo Black — heavy grotesk", "Archivo-Variable.ttf", 900, 1.05),
    # ── Reciter: light sans ──
    _r("cormorant_garamond", "Cormorant Garamond — light classic", "CormorantGaramond-Variable.ttf", 300),
    _r("josefin_sans", "Josefin Sans — art-deco geometric", "JosefinSans-Variable.ttf", 300),
    _r("raleway", "Raleway — elegant thin", "Raleway-Variable.ttf", 300),
    _r("outfit", "Outfit — rounded modern", "Outfit-Variable.ttf", 300),
    _r("space_grotesk", "Space Grotesk — tech editorial", "SpaceGrotesk-Variable.ttf", 400),
    _r("eb_garamond_italic", "EB Garamond Italic — literary", "EBGaramond-Italic-Variable.ttf", 400),
    _r("tenor_sans", "Tenor Sans — whisper caps", "TenorSans-Regular.ttf", size_scale=1.08),
    _r("sora", "Sora — crisp minimal", "Sora-Variable.ttf", 300),
    _r("lexend", "Lexend — readability tuned", "Lexend-Variable.ttf", 400),
    _r("libre_franklin", "Libre Franklin — newsroom", "LibreFranklin-Variable.ttf", 300),
    _r("spectral", "Spectral — bookish serif", "Spectral-Regular.ttf"),
    _r("lora_light", "Lora — warm subtitle", "Lora-Variable.ttf", 400),
    _r("catamaran", "Catamaran — tropical humanist", "Catamaran-Variable.ttf", 400),
    _r("quicksand", "Quicksand — soft friendly", "Quicksand-Variable.ttf", 400),
    _r("cormorant_light", "Cormorant — airy serif", "Cormorant-Variable.ttf", 300),
    _r("jost", "Jost — European geometric", "Jost-Variable.ttf", 300),
    _r("montserrat", "Montserrat — clean geometric", "Montserrat-Variable.ttf", 300),
    _r("nunito_sans", "Nunito Sans — soft rounded", "NunitoSans-Variable.ttf", 300),
    _r("source_sans", "Source Sans 3 — neutral pro", "SourceSans3-Variable.ttf", 300),
    _r("inter", "Inter — UI clarity", "Inter-Variable.ttf", 300),
    _r("dm_sans", "DM Sans — friendly pro", "DMSans-Variable.ttf", 400),
    _r("karla", "Karla — warm grotesk", "Karla-Variable.ttf", 300),
    _r("manrope", "Manrope — soft geometric", "Manrope-Variable.ttf", 400),
    _r("open_sans", "Open Sans — universal", "OpenSans-Variable.ttf", 300),
    _r("poppins_light", "Poppins Light — sleek", "Poppins-Light.ttf"),
    _r("mulish", "Mulish — minimal grotesk", "Mulish-Variable.ttf", 300),
    _r("figtree", "Figtree — contemporary UI", "Figtree-Variable.ttf", 400),
    _r("cabin", "Cabin — humanist sans", "Cabin-Variable.ttf", 400),
    _r("work_sans", "Work Sans — balanced", "WorkSans-Variable.ttf", 300),
    _r("public_sans", "Public Sans — gov readable", "PublicSans-Variable.ttf", 400),
    _r("albert_sans", "Albert Sans — geometric neutral", "AlbertSans-Variable.ttf", 400),
    _r("commissioner", "Commissioner — variable grotesk", "Commissioner-Variable.ttf", 400),
    _r("rubik", "Rubik — rounded modern", "Rubik-Variable.ttf", 300),
    _r("urbanist", "Urbanist — geometric clean", "Urbanist-Variable.ttf", 300),
    _r("plus_jakarta", "Plus Jakarta Sans — startup sleek", "PlusJakartaSans-Variable.ttf", 400),
    _r("red_hat_display", "Red Hat Display — open pro", "RedHatDisplay-Variable.ttf", 400),
    _r("barlow", "Barlow — wide friendly", "Barlow-Variable.ttf", 400),
    _r("exo2", "Exo 2 — futuristic", "Exo2-Variable.ttf", 300),
    _r("overpass", "Overpass — highway gothic", "Overpass-Variable.ttf", 400),
    _r("titillium", "Titillium Web — tech humanist", "TitilliumWeb-Variable.ttf", 400),
    _r("ubuntu", "Ubuntu — Linux humanist", "Ubuntu-Variable.ttf", 300),
    _r("asap", "Asap — rounded grotesk", "Asap-Variable.ttf", 400),
    _r("archivo", "Archivo — grotesk news", "Archivo-Variable.ttf", 400),
    _r("archivo_narrow", "Archivo Narrow — compact news", "ArchivoNarrow-Variable.ttf", 400),
    _r("assistant", "Assistant — Hebrew-Latin", "Assistant-Variable.ttf", 400),
    _r("atkinson", "Atkinson Hyperlegible — accessible", "AtkinsonHyperlegible-Variable.ttf", 400),
    _r("chivo", "Chivo — Mexican grotesk", "Chivo-Variable.ttf", 400),
    _r("dark_grotesque", "Darker Grotesque — editorial", "DarkerGrotesque-Variable.ttf", 400),
    _r("encode_sans", "Encode Sans — modular", "EncodeSans-Variable.ttf", 300),
    _r("epilogue", "Epilogue — variable UI", "Epilogue-Variable.ttf", 400),
    _r("familjen", "Familjen Grotesk — Swedish", "FamiljenGrotesk-Variable.ttf", 400),
    _r("golos", "Golos Text — Russian UI", "GolosText-Variable.ttf", 400),
    _r("heebo", "Heebo — Hebrew modern", "Heebo-Variable.ttf", 400),
    _r("hind", "Hind — Devanagari-Latin", "Hind-Variable.ttf", 400),
    _r("ibm_plex_sans", "IBM Plex Sans — corporate", "IBMPlexSans-Variable.ttf", 300),
    _r("kanit", "Kanit — Thai-Latin", "Kanit-Variable.ttf", 300),
    _r("lato", "Lato — humanist classic", "Lato-Variable.ttf", 300),
    _r("league_spartan", "League Spartan — geometric", "LeagueSpartan-Variable.ttf", 400),
    _r("libre_caslon", "Libre Caslon Text — traditional", "LibreCaslonText-Variable.ttf", 400),
    _r("mada", "Mada — Arabic-Latin", "Mada-Variable.ttf", 400),
    _r("mplus1p", "M PLUS 1p — Japanese UI", "MPLUS1p-Variable.ttf", 400),
    _r("mukta", "Mukta — Devanagari-Latin", "Mukta-Variable.ttf", 400),
    _r("nanum_gothic", "Nanum Gothic — Korean UI", "NanumGothic-Variable.ttf", 400),
    _r("noto_sans_display", "Noto Sans Display — large sizes", "NotoSansDisplay-Variable.ttf", 400),
    _r("nunito", "Nunito — rounded friendly", "Nunito-Variable.ttf", 400),
    _r("oxygen", "Oxygen — KDE humanist", "Oxygen-Variable.ttf", 400),
    _r("pontano_sans", "Pontano Sans — soft geometric", "PontanoSans-Variable.ttf", 400),
    _r("prompt", "Prompt — Thai-Latin", "Prompt-Variable.ttf", 300),
    _r("proza_libre", "Proza Libre — book sans", "ProzaLibre-Variable.ttf", 400),
    _r("questrial", "Questrial — geometric clean", "Questrial-Variable.ttf", 400),
    _r("radio_canada", "Radio Canada — CBC brand", "RadioCanada-Variable.ttf", 400),
    _r("red_hat_text", "Red Hat Text — body sans", "RedHatText-Variable.ttf", 400),
    _r("roboto", "Roboto — Android default", "Roboto-Variable.ttf", 400),
    _r("roboto_condensed", "Roboto Condensed — narrow", "RobotoCondensed-Variable.ttf", 400),
    _r("rufina", "Rufina — serif subtitle", "Rufina-Regular.ttf"),
    _r("sarabun", "Sarabun — Thai clean", "Sarabun-Variable.ttf", 300),
    _r("signika", "Signika — soft signage", "Signika-Variable.ttf", 400),
    _r("syne", "Syne — art-house", "Syne-Variable.ttf", 400),
    _r("teko", "Teko — Devanagari-Latin", "Teko-Variable.ttf", 400),
    _r("thasadith", "Thasadith — Thai light", "Thasadith-Variable.ttf", 400),
    _r("voltaire", "Voltaire — flat geometric", "Voltaire-Regular.ttf"),
    _r("wix_display", "Wix Madefor Display — brand UI", "WixMadeforDisplay-Variable.ttf", 400),
    _r("wix_text", "Wix Madefor Text — brand body", "WixMadeforText-Variable.ttf", 400),
    _r("yantramanav", "Yantramanav — Devanagari UI", "Yantramanav-Variable.ttf", 400),
    _r("zen_kaku", "Zen Kaku Gothic — Japanese UI", "ZenKakuGothicNew-Variable.ttf", 400),
    _r("varta", "Varta — Telugu-Latin", "Varta-Variable.ttf", 400),
    _r("sen", "Sen — geometric Malayalam", "Sen-Variable.ttf", 400),
    _r("share_tech", "Share Tech — sci-fi light", "ShareTech-Regular.ttf"),
    _r("share_tech_mono", "Share Tech Mono — sci-fi mono", "ShareTechMono-Regular.ttf", size_scale=0.92),
    _r("short_stack", "Short Stack — casual hand", "ShortStack-Regular.ttf"),
    _r("silkscreen", "Silkscreen — pixel body", "Silkscreen-Regular.ttf", size_scale=0.9),
    _r("sniglet", "Sniglet — rounded display", "Sniglet-Regular.ttf"),
    _r("quattrocento_sans", "Quattrocento Sans — humanist", "QuattrocentoSans-Regular.ttf"),
    _r("rajdhani", "Rajdhani — Devanagari-Latin", "Rajdhani-Regular.ttf"),
    _r("reem_kufi_light", "Reem Kufi — Arabic subtitle", "ReemKufi-Variable.ttf", 400),
    _r("metrophobic", "Metrophobic — geometric thin", "Metrophobic-Regular.ttf"),
    _r("mirza", "Mirza — Arabic-Latin", "Mirza-Regular.ttf"),
    _r("mitr", "Mitr — Thai rounded", "Mitr-Regular.ttf"),
    _r("imprima", "Imprima — soft humanist", "Imprima-Regular.ttf"),
    _r("lemonada", "Lemonada — Arabic rounded", "Lemonada-Variable.ttf", 400),
    _r("mclaren", "McLaren — rounded display", "McLaren-Regular.ttf"),
    _r("portlligat", "Port Lligat Sans — thin art", "PortLligatSans-Regular.ttf", size_scale=1.1),
    _r("sarala", "Sarala — Devanagari-Latin", "Sarala-Regular.ttf"),
    _r("sail", "Sail — display serif light", "Sail-Regular.ttf"),
    _r("sanchez", "Sanchez — slab subtitle", "Sanchez-Regular.ttf"),
    _r("raleway_dots", "Raleway Dots — dotted art", "RalewayDots-Regular.ttf", size_scale=1.05),
    _r("fanwood_reciter", "Fanwood Text — vintage subtitle", "FanwoodText-Italic.ttf"),
    _r("halant_reciter", "Halant — Devanagari subtitle", "Halant-Regular.ttf"),
    _r("oleo_reciter", "Oleo Script — script subtitle", "OleoScript-Regular.ttf"),
    _r("philosopher_reciter", "Philosopher — mystical light", "Philosopher-Regular.ttf"),
    _r("poppins_reg", "Poppins — modern geometric", "Poppins-Regular.ttf"),
)

TITLE_FONTS = tuple(d for d in FONT_REGISTRY if "title" in d.roles)
RECITER_FONTS = tuple(d for d in FONT_REGISTRY if "reciter" in d.roles)

ESSENTIAL_FONT_FILES: frozenset[str] = frozenset({
    "Amiri-Bold.ttf",
    "Cinzel-Variable.ttf",
    "CormorantGaramond-Variable.ttf",
    "PlayfairDisplay-Variable.ttf",
    "JosefinSans-Variable.ttf",
    "NotoSans-Variable.ttf",
    "NotoSansSC-Variable.ttf",
    "NotoSansJP-Variable.ttf",
    "NotoSansKR-Variable.ttf",
    "NotoSansDevanagari-Variable.ttf",
    "NotoSansBengali-Variable.ttf",
    "NotoNaskhArabic-Variable.ttf",
})
