"""All 114 Quranic surahs with Arabic and English display names."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Surah:
    number: int
    arabic: str
    english: str


SURAHS: list[Surah] = [
    Surah(1, "سورة الفاتحة", "Surah Al-Fatiha"),
    Surah(2, "سورة البقرة", "Surah Al-Baqarah"),
    Surah(3, "سورة آل عمران", "Surah Ali 'Imran"),
    Surah(4, "سورة النساء", "Surah An-Nisa"),
    Surah(5, "سورة المائدة", "Surah Al-Ma'idah"),
    Surah(6, "سورة الأنعام", "Surah Al-An'am"),
    Surah(7, "سورة الأعراف", "Surah Al-A'raf"),
    Surah(8, "سورة الأنفال", "Surah Al-Anfal"),
    Surah(9, "سورة التوبة", "Surah At-Tawbah"),
    Surah(10, "سورة يونس", "Surah Yunus"),
    Surah(11, "سورة هود", "Surah Hud"),
    Surah(12, "سورة يوسف", "Surah Yusuf"),
    Surah(13, "سورة الرعد", "Surah Ar-Ra'd"),
    Surah(14, "سورة إبراهيم", "Surah Ibrahim"),
    Surah(15, "سورة الحجر", "Surah Al-Hijr"),
    Surah(16, "سورة النحل", "Surah An-Nahl"),
    Surah(17, "سورة الإسراء", "Surah Al-Isra"),
    Surah(18, "سورة الكهف", "Surah Al-Kahf"),
    Surah(19, "سورة مريم", "Surah Maryam"),
    Surah(20, "سورة طه", "Surah Ta-Ha"),
    Surah(21, "سورة الأنبياء", "Surah Al-Anbiya"),
    Surah(22, "سورة الحج", "Surah Al-Hajj"),
    Surah(23, "سورة المؤمنون", "Surah Al-Mu'minun"),
    Surah(24, "سورة النور", "Surah An-Nur"),
    Surah(25, "سورة الفرقان", "Surah Al-Furqan"),
    Surah(26, "سورة الشعراء", "Surah Ash-Shu'ara"),
    Surah(27, "سورة النمل", "Surah An-Naml"),
    Surah(28, "سورة القصص", "Surah Al-Qasas"),
    Surah(29, "سورة العنكبوت", "Surah Al-Ankabut"),
    Surah(30, "سورة الروم", "Surah Ar-Rum"),
    Surah(31, "سورة لقمان", "Surah Luqman"),
    Surah(32, "سورة السجدة", "Surah As-Sajdah"),
    Surah(33, "سورة الأحزاب", "Surah Al-Ahzab"),
    Surah(34, "سورة سبأ", "Surah Saba"),
    Surah(35, "سورة فاطر", "Surah Fatir"),
    Surah(36, "سورة يس", "Surah Ya-Sin"),
    Surah(37, "سورة الصافات", "Surah As-Saffat"),
    Surah(38, "سورة ص", "Surah Sad"),
    Surah(39, "سورة الزمر", "Surah Az-Zumar"),
    Surah(40, "سورة غافر", "Surah Ghafir"),
    Surah(41, "سورة فصلت", "Surah Fussilat"),
    Surah(42, "سورة الشورى", "Surah Ash-Shura"),
    Surah(43, "سورة الزخرف", "Surah Az-Zukhruf"),
    Surah(44, "سورة الدخان", "Surah Ad-Dukhan"),
    Surah(45, "سورة الجاثية", "Surah Al-Jathiyah"),
    Surah(46, "سورة الأحقاف", "Surah Al-Ahqaf"),
    Surah(47, "سورة محمد", "Surah Muhammad"),
    Surah(48, "سورة الفتح", "Surah Al-Fath"),
    Surah(49, "سورة الحجرات", "Surah Al-Hujurat"),
    Surah(50, "سورة ق", "Surah Qaf"),
    Surah(51, "سورة الذاريات", "Surah Adh-Dhariyat"),
    Surah(52, "سورة الطور", "Surah At-Tur"),
    Surah(53, "سورة النجم", "Surah An-Najm"),
    Surah(54, "سورة القمر", "Surah Al-Qamar"),
    Surah(55, "سورة الرحمن", "Surah Ar-Rahman"),
    Surah(56, "سورة الواقعة", "Surah Al-Waqi'ah"),
    Surah(57, "سورة الحديد", "Surah Al-Hadid"),
    Surah(58, "سورة المجادلة", "Surah Al-Mujadila"),
    Surah(59, "سورة الحشر", "Surah Al-Hashr"),
    Surah(60, "سورة الممتحنة", "Surah Al-Mumtahanah"),
    Surah(61, "سورة الصف", "Surah As-Saf"),
    Surah(62, "سورة الجمعة", "Surah Al-Jumu'ah"),
    Surah(63, "سورة المنافقون", "Surah Al-Munafiqun"),
    Surah(64, "سورة التغابن", "Surah At-Taghabun"),
    Surah(65, "سورة الطلاق", "Surah At-Talaq"),
    Surah(66, "سورة التحريم", "Surah At-Tahrim"),
    Surah(67, "سورة الملك", "Surah Al-Mulk"),
    Surah(68, "سورة القلم", "Surah Al-Qalam"),
    Surah(69, "سورة الحاقة", "Surah Al-Haqqah"),
    Surah(70, "سورة المعارج", "Surah Al-Ma'arij"),
    Surah(71, "سورة نوح", "Surah Nuh"),
    Surah(72, "سورة الجن", "Surah Al-Jinn"),
    Surah(73, "سورة المزمل", "Surah Al-Muzzammil"),
    Surah(74, "سورة المدثر", "Surah Al-Muddaththir"),
    Surah(75, "سورة القيامة", "Surah Al-Qiyamah"),
    Surah(76, "سورة الإنسان", "Surah Al-Insan"),
    Surah(77, "سورة المرسلات", "Surah Al-Mursalat"),
    Surah(78, "سورة النبأ", "Surah An-Naba"),
    Surah(79, "سورة النازعات", "Surah An-Nazi'at"),
    Surah(80, "سورة عبس", "Surah Abasa"),
    Surah(81, "سورة التكوير", "Surah At-Takwir"),
    Surah(82, "سورة الانفطار", "Surah Al-Infitar"),
    Surah(83, "سورة المطففين", "Surah Al-Mutaffifin"),
    Surah(84, "سورة الانشقاق", "Surah Al-Inshiqaq"),
    Surah(85, "سورة البروج", "Surah Al-Buruj"),
    Surah(86, "سورة الطارق", "Surah At-Tariq"),
    Surah(87, "سورة الأعلى", "Surah Al-A'la"),
    Surah(88, "سورة الغاشية", "Surah Al-Ghashiyah"),
    Surah(89, "سورة الفجر", "Surah Al-Fajr"),
    Surah(90, "سورة البلد", "Surah Al-Balad"),
    Surah(91, "سورة الشمس", "Surah Ash-Shams"),
    Surah(92, "سورة الليل", "Surah Al-Layl"),
    Surah(93, "سورة الضحى", "Surah Ad-Duha"),
    Surah(94, "سورة الشرح", "Surah Ash-Sharh"),
    Surah(95, "سورة التين", "Surah At-Tin"),
    Surah(96, "سورة العلق", "Surah Al-Alaq"),
    Surah(97, "سورة القدر", "Surah Al-Qadr"),
    Surah(98, "سورة البينة", "Surah Al-Bayyinah"),
    Surah(99, "سورة الزلزلة", "Surah Az-Zalzalah"),
    Surah(100, "سورة العاديات", "Surah Al-Adiyat"),
    Surah(101, "سورة القارعة", "Surah Al-Qari'ah"),
    Surah(102, "سورة التكاثر", "Surah At-Takathur"),
    Surah(103, "سورة العصر", "Surah Al-Asr"),
    Surah(104, "سورة الهمزة", "Surah Al-Humazah"),
    Surah(105, "سورة الفيل", "Surah Al-Fil"),
    Surah(106, "سورة قريش", "Surah Quraysh"),
    Surah(107, "سورة الماعون", "Surah Al-Ma'un"),
    Surah(108, "سورة الكوثر", "Surah Al-Kawthar"),
    Surah(109, "سورة الكافرون", "Surah Al-Kafirun"),
    Surah(110, "سورة النصر", "Surah An-Nasr"),
    Surah(111, "سورة المسد", "Surah Al-Masad"),
    Surah(112, "سورة الإخلاص", "Surah Al-Ikhlas"),
    Surah(113, "سورة الفلق", "Surah Al-Falaq"),
    Surah(114, "سورة الناس", "Surah An-Nas"),
]

SURAH_BY_NUMBER = {surah.number: surah for surah in SURAHS}


def get_surah(number: int) -> Surah | None:
    return SURAH_BY_NUMBER.get(number)


def surah_label(surah: Surah) -> str:
    return f"{surah.number}. {surah.english.replace('Surah ', '')}"
